//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7
use anyhow::Result;
use chrono::{DateTime, Utc};
use primitive_types::U256;
use sea_orm::{entity::prelude::*, ActiveValue::NotSet, Set};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "census_node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub census_id: i32,
    pub record_id: i32,
    pub surveyed_at: DateTime<Utc>,
    pub data_radius: Vec<u8>,
    pub data_radius_high: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::census::Entity",
        from = "Column::CensusId",
        to = "super::census::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Census,
}

impl Related<super::census::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Census.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn create(
    census_id: i32,
    record_id: i32,
    data_radius: U256,
    surveyed_at: DateTime<Utc>,
    conn: &DatabaseConnection,
) -> Result<Model> {
    let data_radius_high: i64 = (data_radius >> 193).as_u64().try_into().unwrap();
    let data_radius_raw: [u8; 32] = data_radius.into();

    let census = ActiveModel {
        id: NotSet,
        census_id: Set(census_id),
        record_id: Set(record_id),
        surveyed_at: Set(surveyed_at),
        data_radius: Set(data_radius_raw.into()),
        data_radius_high: Set(data_radius_high),
    };

    Ok(census.insert(conn).await?)
}
