//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7
use anyhow::Result;
use ethportal_api::types::enr::Enr;
use sea_orm::{entity::prelude::*, ActiveValue::NotSet, Set};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version: String,
    pub node_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::content_audit::Entity")]
    ContentAudit,
    #[sea_orm(
        belongs_to = "super::node::Entity",
        from = "Column::NodeId",
        to = "super::node::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Node,
}

impl Related<super::content_audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentAudit.def()
    }
}

impl Related<super::node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Node.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_or_create(version: String, enr: &Enr, conn: &DatabaseConnection) -> Result<Model> {
    let record = super::record::get_or_create(enr, conn).await?;

    // First try to lookup an existing entry.
    if let Some(client_info_model) = Entity::find()
        .filter(Column::NodeId.eq(record.node_id))
        .filter(Column::Version.eq(&version))
        .one(conn)
        .await?
    {
        // If there is an existing record, return it
        return Ok(client_info_model);
    }

    // If no record exists, create one and return it
    let client_info_model = ActiveModel {
        id: NotSet,
        version: Set(version),
        node_id: Set(record.node_id),
    };
    Ok(client_info_model.insert(conn).await.unwrap())
}
