//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use ethportal_api::types::{enr::Enr, protocol_versions::ProtocolVersionList};
use sea_orm::{entity::prelude::*, NotSet, Set};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "node_enr")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub node_id: i32,
    #[sea_orm(column_type = "Text")]
    pub raw: String,
    pub sequence_number: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::N(32))")]
    pub protocol_versions: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit_transfer_failure::Entity")]
    AuditTransferFailure,
    #[sea_orm(has_many = "super::census_node::Entity")]
    CensusNode,
    #[sea_orm(
        belongs_to = "super::node::Entity",
        from = "Column::NodeId",
        to = "super::node::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Node,
}

impl Related<super::audit_transfer_failure::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditTransferFailure.def()
    }
}

impl Related<super::census_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CensusNode.def()
    }
}

impl Related<super::node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Node.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

// *** Custom additions ***

pub async fn get_or_create(enr: &Enr, conn: &DatabaseConnection) -> Result<Model, DbErr> {
    let node_model = super::node::get_or_create(enr.node_id(), conn).await?;
    let seq = enr.seq() as i64;

    // First try to lookup an existing entry.
    if let Some(enr_model) = Entity::find()
        .filter(Column::NodeId.eq(node_model.id))
        .filter(Column::SequenceNumber.eq(seq))
        .one(conn)
        .await?
    {
        // If there is an existing record, return it
        return Ok(enr_model);
    }

    // If no record exists, create one and return it
    let protocol_versions = enr
        .get_decodable::<ProtocolVersionList>("pv")
        .and_then(Result::ok)
        .map(|protocol_version_list| protocol_version_list.0.into_iter().map(u8::from).collect())
        .unwrap_or_default();

    let enr_model_unsaved = ActiveModel {
        id: NotSet,
        node_id: Set(node_model.id),
        raw: Set(enr.to_base64()),
        sequence_number: Set(seq),
        protocol_versions: Set(protocol_versions),
    };

    enr_model_unsaved.insert(conn).await
}
