//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7
use std::collections::HashMap;

use alloy_primitives::U256;
use anyhow::Result;
use enr::NodeId;
use ethportal_api::utils::bytes::hex_encode;

use sea_orm::{
    entity::prelude::*, ActiveValue::NotSet, FromQueryResult, QueryOrder, QuerySelect, Set,
};
use sea_query::Expr;

use lazy_static::lazy_static;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub node_id: Vec<u8>,
    pub node_id_high: i64,
}

impl Model {
    pub fn node_id_as_hex(&self) -> String {
        hex_encode(&self.node_id)
    }

    pub fn get_node_id(&self) -> NodeId {
        let mut node_id = [0u8; 32];
        node_id.copy_from_slice(&self.node_id);
        NodeId::new(&node_id)
    }

    pub fn get_nickname(&self) -> Option<String> {
        NODE_NICKNAME_MAP.get(&self.node_id_as_hex()).cloned()
    }
}

#[derive(FromQueryResult)]
pub struct ModelWithDistance {
    pub id: i32,
    pub node_id: Vec<u8>,
    pub node_id_high: i64,
    pub distance: i64,
}

impl ModelWithDistance {
    pub fn node_id_as_hex(&self) -> String {
        hex_encode(&self.node_id)
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::record::Entity")]
    Record,
    #[sea_orm(has_one = "super::client_info::Entity")]
    ClientInfo,
}

impl Related<super::record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Record.def()
    }
}

impl Related<super::client_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
enum ComputedColumn {
    Distance,
}

impl ColumnTrait for ComputedColumn {
    type EntityName = Entity;

    fn def(&self) -> ColumnDef {
        match self {
            Self::Distance => ColumnType::Integer.def(),
        }
    }
}

pub async fn closest_xor(
    node_id: NodeId,
    conn: &DatabaseConnection,
) -> Result<Vec<ModelWithDistance>> {
    let raw_node_id = U256::from_be_slice(&node_id.raw());
    let node_id_high: i64 = raw_node_id.wrapping_shr(193).to::<i64>();

    let distance_expression = Expr::cust_with_values(
        "(\"node\".\"node_id_high\" | $1) - (\"node\".\"node_id_high\" & $2)",
        [node_id_high, node_id_high],
    );

    let nodes = Entity::find()
        .column_as(distance_expression, "distance")
        .order_by_asc(Expr::col(ComputedColumn::Distance))
        .limit(100)
        .into_model::<ModelWithDistance>()
        .all(conn)
        .await?;
    Ok(nodes)
}

pub async fn get_or_create(node_id: NodeId, conn: &DatabaseConnection) -> Result<Model> {
    // First try to lookup an existing entry.
    if let Some(node_id_model) = Entity::find()
        .filter(Column::NodeId.eq(node_id.raw().to_vec()))
        .one(conn)
        .await?
    {
        // If there is an existing record, return it
        return Ok(node_id_model);
    }

    // If no record exists, create one and return it
    let raw_node_id = U256::from_be_slice(&node_id.raw());
    let node_id_high: i64 = raw_node_id.wrapping_shr(193).to::<i64>();

    let node_id_model = ActiveModel {
        id: NotSet,
        node_id: Set(node_id.raw().into()),
        node_id_high: Set(node_id_high),
    };

    Ok(node_id_model.insert(conn).await?)
}

lazy_static! {
    pub static ref NODE_NICKNAME_MAP: HashMap<String, String> = {
        let mut nicknames = HashMap::<String, String>::new();
        nicknames.insert(
            "0x5ce3d0e0c0617c0a72b0fa237f8d5913fff0ebd89bc54cd68d95e1669cd9306f".to_string(),
            "trin-ams3-2".to_string(),
        );
        nicknames.insert(
            "0x12268d53c44e6c1aae1ec9bc8ab401c4da776fc7fe6f0ad00f273b4adc7ad872".to_string(),
            "trin-nyc1-2".to_string(),
        );
        nicknames.insert(
            "0x290c187ddc44dfeeb2cdf9d30697a030698dfad2d150d037080c523761f410a5".to_string(),
            "trin-sgp1-2".to_string(),
        );
        nicknames.insert(
            "0x794cbd50977f0b202db565d292d0ca8377cebc3497eaea21822afd967e7d2364".to_string(),
            "trin-nyc1-18".to_string(),
        );
        nicknames.insert(
            "0x4c9e465f50376783c3f91e7c3526cf948b1d82938e0fad3ba07b5abff1e2f4e7".to_string(),
            "trin-ams3-13".to_string(),
        );
        nicknames.insert(
            "0x146905875ac8df6dce7d7b93860adf7b06ea051db7dd52c285aa85049f4d8b05".to_string(),
            "trin-nyc1-6".to_string(),
        );
        nicknames.insert(
            "0xc56aea96614f4b1415a637fbbb070ee80ac25a988b41755a0ff6b38e566343a5".to_string(),
            "trin-nyc1-27".to_string(),
        );
        nicknames.insert(
            "0x0361e3264aa208e555e07292320ff4bf8d14c61a1cdc89841b47cd805d4fc338".to_string(),
            "trin-nyc1-4".to_string(),
        );
        nicknames.insert(
            "0xe95d9c2686eb7d7e2fe6767ba7aa3a8bde7b1c2a8d13644b8babaea26b2c0c09".to_string(),
            "trin-ams3-32".to_string(),
        );
        nicknames.insert(
            "0xaec32459fccc67fe540be30d68169b753fe70144fc5596824a623ba5942ee66b".to_string(),
            "trin-sgp1-24".to_string(),
        );
        nicknames.insert(
            "0xba1647ae9a93d575a3c1d700774dc4d6e71fe2b85f2eb90b286d62b6602ed5cf".to_string(),
            "trin-ams3-26".to_string(),
        );
        nicknames.insert(
            "0x8dac04562791694e89b5e28118512aeb60680a0a622484b9be51bfc9a98881d5".to_string(),
            "trin-sgp1-20".to_string(),
        );
        nicknames.insert(
            "0x9ea4a21e76c31532001768d2881ac816a7bcfc96fdb3a618d2243b16ed47a270".to_string(),
            "trin-sgp1-22".to_string(),
        );
        nicknames.insert(
            "0x490af454caeab270b3a75b7f14f1360e98da78aa9587e6d867964d879fa0f917".to_string(),
            "trin-sgp1-12".to_string(),
        );
        nicknames.insert(
            "0x3b84fc0e4399d3239a625b4cf210e3dcdad0884606b5b62b787c7cae0173a5eb".to_string(),
            "trin-ams3-11".to_string(),
        );
        nicknames.insert(
            "0x623d63b5f621a5daa09b110faa38b7e59847c06af90865476850c6e7a70644e6".to_string(),
            "trin-sgp1-15".to_string(),
        );
        nicknames.insert(
            "0x73d13b449b82209e2ba37da292979643d38dfb961e8c28150d94e696b8a12f1c".to_string(),
            "trin-sgp1-17".to_string(),
        );
        nicknames.insert(
            "0x0632ff9510d10a19587db911d6b5d571fc323e50553c3f5efa2a813a0aadb141".to_string(),
            "trin-sgp1-4".to_string(),
        );
        nicknames.insert(
            "0x00aaad5ba24375811f58cd56d04050a1b5238cea340005e6a207ea3653ee9d61".to_string(),
            "trin-ams3-1 (bootnode)".to_string(),
        );
        nicknames.insert(
            "0x2dce06489dcb5d604984e9eaa6ab3296b0e3a8c2da612d150ecf0cd736040b2b".to_string(),
            "trin-nyc1-9".to_string(),
        );
        nicknames.insert(
            "0xcb15ca45a4ec0732775e5b1f2152d02194f262ace714298b96e54097a8415ef6".to_string(),
            "trin-ams3-28".to_string(),
        );
        nicknames.insert(
            "0xd9e519275542f78b61bad173a33a9ca047f4b6f2b07fcfd0314be145579ae280".to_string(),
            "trin-sgp1-29".to_string(),
        );
        nicknames.insert(
            "0x30c1ceb0ccc2448a674b73d573924743ce7622ae112b6fe74666fc01ca0cea4f".to_string(),
            "trin-sgp1-9".to_string(),
        );
        nicknames.insert(
            "0x0b5b4972f32734bb5a2c4e80d4805de26068755e26b50317221fcecd8bd8ad9c".to_string(),
            "trin-nyc1-5".to_string(),
        );
        nicknames.insert(
            "0xfae241338ae8cdd6296e7014877a81848b8e385381bbfcd51b745ef94c09343a".to_string(),
            "trin-ams3-35".to_string(),
        );
        nicknames.insert(
            "0xec1a6d36937e5ae64033f65b805597d0175c0fd3bf236d2dd907e71ce3dc3e3a".to_string(),
            "trin-nyc1-32".to_string(),
        );
        nicknames.insert(
            "0xf2e268333e4ce7286925797da743de0271a43c6a4e0fc61310e397782f022be1".to_string(),
            "trin-nyc1-33".to_string(),
        );
        nicknames.insert(
            "0xb4fbb3a59ecbdeb8396ad398e337b6885beeb1cbb0d00ea9867b33ae85811a0a".to_string(),
            "trin-nyc1-25".to_string(),
        );
        nicknames.insert(
            "0xbffe12db62975395c67d0d2b93495da34e84f6d59984506695d3bb59950ef9ea".to_string(),
            "trin-sgp1-26".to_string(),
        );
        nicknames.insert(
            "0xac9c85b2d013331f397a6eb167e61d9b0c78a610e662e4569e3ee8609a37ee43".to_string(),
            "trin-nyc1-24".to_string(),
        );
        nicknames.insert(
            "0xa63686a8535ffda3f9e5bae54b81e747ed51f185dc0d8777c47905580f587c00".to_string(),
            "trin-sgp1-23".to_string(),
        );
        nicknames.insert(
            "0x8fa77313f6ae5536c9466a7bde1348ff10be4c972015efd190804f3b852bc012".to_string(),
            "trin-ams3-21".to_string(),
        );
        nicknames.insert(
            "0x41549f7182d561154aa35b24bba05dbe2085fb349af4ddaaf806ab5ebd180d9b".to_string(),
            "trin-sgp1-11".to_string(),
        );
        nicknames.insert(
            "0x17cefdd4dc9e3bf8128db908803f00e3e547e3b94a189d78f29c5b79dddaf937".to_string(),
            "trin-sgp1-6".to_string(),
        );
        nicknames.insert(
            "0x1f8592ca7afbdf5a0ae4afb79b7af4f2dc82de50432f94517f7d10ac39b24b92".to_string(),
            "trin-sgp1-7".to_string(),
        );
        nicknames.insert(
            "0x2774d76e8d08abf46b93c2c2a82b6828b63c7108b47a2bde40c4a4fb3329fc3a".to_string(),
            "trin-sgp1-8".to_string(),
        );
        nicknames.insert(
            "0xc20a9b0c7405ffc08da06ef9f2ffc44d38d0f2efcc7e3f7eb520625ca892755e".to_string(),
            "trin-ams3-27".to_string(),
        );
        nicknames.insert(
            "0xd3a47990b3ff8f8bf39928dff9739fe676daa65ad51e84d7b0b3199107f64d2f".to_string(),
            "trin-ams3-29".to_string(),
        );
        nicknames.insert(
            "0xde5166991494ce1a8c11eb5f87104e9085a0844833b18543db3a3fc6ed7fed5d".to_string(),
            "trin-nyc1-30".to_string(),
        );
        nicknames.insert(
            "0xe1ccb68a3417504bdbf3ad0df1c06a911bbc1c29fe84df81ef64f28f0727bc86".to_string(),
            "trin-sgp1-30".to_string(),
        );
        nicknames.insert(
            "0xb1f4814c692b165352fdb27964b284d88a588b9f3d734748d3652f311ce15d2f".to_string(),
            "trin-ams3-25".to_string(),
        );
        nicknames.insert(
            "0xa0cd2d177067f663bd06b351219591ec0bab274f020e0964035a3006d47c298a".to_string(),
            "trin-ams3-23".to_string(),
        );
        nicknames.insert(
            "0xa9c1a8e585e1347175444a1252cc3acce9bb69f4e91ca94958700e9ed11ad45b".to_string(),
            "trin-ams3-24".to_string(),
        );
        nicknames.insert(
            "0x984948788690c4f8f13fdb5b7fbb6998f803f7b0deff2d128d9d1cfba49874cb".to_string(),
            "trin-ams3-22".to_string(),
        );
        nicknames.insert(
            "0x8767d6952ab1bea701cbf6fe70922faf63a6ad2c4128f0369f6fe74a331012aa".to_string(),
            "trin-ams3-20".to_string(),
        );
        nicknames.insert(
            "0x8a9e7cabe2611597080e6b6a6d90719d1484af9f0df9f729d776ec92b9acdaf7".to_string(),
            "trin-nyc1-20".to_string(),
        );
        nicknames.insert(
            "0x7f36f2ab4183c5644e999c305a832ed80d1b00c6d12435a39f37dfc8227c34f0".to_string(),
            "trin-ams3-19".to_string(),
        );
        nicknames.insert(
            "0x556d556773b369686055b1a79b52e0629f3cd4369a0ba505c3eae3c4b97fb0c7".to_string(),
            "trin-nyc1-1 (bootnode)".to_string(),
        );
        nicknames.insert(
            "0xf8368f60ee86532cd3990806a356468fc12139791ebf1e6b29d30eedab89f841".to_string(),
            "trin-nyc1-34".to_string(),
        );
        nicknames.insert(
            "0x9223dde3ed71f62f938c7fc6841f4ca34048a8d08b79efea689a5546178fa126".to_string(),
            "trin-nyc1-21".to_string(),
        );
        nicknames.insert(
            "0x7cef9dd4ee6549c7847c0f821480cd724c780ff24335c6d90d2c08931935c7ca".to_string(),
            "trin-sgp1-18".to_string(),
        );
        nicknames.insert(
            "0x68ec0487396f017673e26a719d94cc4464e476da0ae3d2aaecf23ceb83389362".to_string(),
            "trin-nyc1-16".to_string(),
        );
        nicknames.insert(
            "0x00b7c1bd815b980a15a100b570f1d18cc161354e3e443bf7662b8cf8f56334cc".to_string(),
            "trin-ams3-4".to_string(),
        );
        nicknames.insert(
            "0x3514da5e6fae802b62dbd381813a4fdd24d208f78506e10e7d94eaac0045354f".to_string(),
            "trin-nyc1-10".to_string(),
        );
        nicknames.insert(
            "0x199af2ea47c67185d35337fa057226f7bfefc0b99f9a7a1cb50ccdc9ced9d5a4".to_string(),
            "trin-ams3-7".to_string(),
        );
        nicknames.insert(
            "0xbc5aea47708d7f5e01f4a21199e9e68aea75a47fca857d96e4fd0ea035b506a1".to_string(),
            "trin-nyc1-26".to_string(),
        );
        nicknames.insert(
            "0x71ada4d33e410cf5b99e854ffe575f7e662b27ed2d6c64c876029e8d2d64f911".to_string(),
            "trin-nyc1-17".to_string(),
        );
        nicknames.insert(
            "0x5d89843cd35753ba791665ac6ff5fb1bec44ae0a90d4a7a9c8c94f9f26ced0c6".to_string(),
            "trin-ams3-15".to_string(),
        );
        nicknames.insert(
            "0x2571e3711ac1dd67a5eca17537d9f04c0af803d0e84544268c80e3c037c2f71e".to_string(),
            "trin-nyc1-8".to_string(),
        );
        nicknames.insert(
            "0x6e96611931a3c7b2d4e9c81c4f5e8e6162e5680fb3a43f41e8cb37ecf1d1616a".to_string(),
            "trin-ams3-17".to_string(),
        );
        nicknames.insert(
            "0x54dd39b782ab69cf2a403c1a5d47533f86f6b9425dd9e1391acac2ad352f5974".to_string(),
            "trin-ams3-14".to_string(),
        );
        nicknames.insert(
            "0x4f725effe6b5b9652c06343fab80123937d94a23695094545816590551c75d86".to_string(),
            "trin-nyc1-13".to_string(),
        );
        nicknames.insert(
            "0x4632ce072a90b4f9db60e98e664357c73df4beab219c2385ee3e4c31f654ce7d".to_string(),
            "trin-nyc1-12".to_string(),
        );
        nicknames.insert(
            "0x5a1252da910bc2b5a0b3799ee41f99af823cea18eeeb683abab5f5e2a61925f6".to_string(),
            "trin-sgp1-14".to_string(),
        );
        nicknames.insert(
            "0x08653f55f8120591717aae0426c10c25f0e6a7db078c2e1516b4f3059cefff35".to_string(),
            "trin-ams3-5".to_string(),
        );
        nicknames.insert(
            "0x112f9793f8396de367ccf3346cf23949380e054645a74f3a5349fcbf275f134e".to_string(),
            "trin-ams3-6".to_string(),
        );
        nicknames.insert(
            "0x2231a55fefd36b87c6efa5e65e15c4dcc75031fa50d5f9d9090b8798a9446585".to_string(),
            "trin-ams3-8".to_string(),
        );
        nicknames.insert(
            "0xc889870632043710fb9014a7e80bb139455f5f238181479311578c464daf30b7".to_string(),
            "trin-sgp1-27".to_string(),
        );
        nicknames.insert(
            "0xd634b398332876cdfdd7d95bdfa157392cbdaa60cd6885f7f0333b8d99f8eecf".to_string(),
            "trin-nyc1-29".to_string(),
        );
        nicknames.insert(
            "0xdb09a78a967871895f39633489236d055b25fb04caec2f57bdeee3646f7a28a1".to_string(),
            "trin-ams3-30".to_string(),
        );
        nicknames.insert(
            "0x444ebedc9cf2c1caf4f28d5caae67276242fb5e0a6400e0a8491e2ed2a17b218".to_string(),
            "trin-ams3-12".to_string(),
        );
        nicknames.insert(
            "0x6530947af4660f597b5c656217c7c8274e54d632c0b9f52c5c6c0851865d3dc6".to_string(),
            "trin-ams3-16".to_string(),
        );
        nicknames.insert(
            "0x572d6806aeaaf0074ce899de10d29df8349e594f4585e6d4deb3e1064b2a1fa3".to_string(),
            "trin-nyc1-14".to_string(),
        );
        nicknames.insert(
            "0x3eb2def71466ddcf233130f016187e4c3d1884e3e7978edd390d8a25fac86e26".to_string(),
            "trin-nyc1-11".to_string(),
        );
        nicknames.insert(
            "0x1cc9a35d8ee4d814eb58817174e5452a616c10c2a1c7c72af5d0d5ada5c8b611".to_string(),
            "trin-nyc1-7".to_string(),
        );
        nicknames.insert(
            "0xd01ef3920ecbb8fecdda9160d4e7a61c8dfc785c1a128a53ccf6c36a535883bd".to_string(),
            "trin-sgp1-28".to_string(),
        );
        nicknames.insert(
            "0xa3ba2c8e50620bb5f3691d6974ff19af90b775ccd4198c016db38b1e9af2b4e8".to_string(),
            "trin-nyc1-23".to_string(),
        );
        nicknames.insert(
            "0xab4ad0cb9fefd03da68bef18ae96e932eebcdb4bb1b4a763e89c5b2bc4212198".to_string(),
            "trin-sgp1-1 (bootnode)".to_string(),
        );
        nicknames.insert(
            "0x95f8b17e1700b74f4ebad4bb5de0564673aeb10b199bd19e65426f7642e9fd3c".to_string(),
            "trin-sgp1-21".to_string(),
        );
        nicknames.insert(
            "0x8452ac5bc378ab275a71e3b891bc770305a2c80dfc4e1f761681c33e4921f9ed".to_string(),
            "trin-sgp1-19".to_string(),
        );
        nicknames.insert(
            "0x6bedd98c677c03e71b43b9860f503940fdf0255a0571a3a52881f0ac045c5d89".to_string(),
            "trin-sgp1-16".to_string(),
        );
        nicknames.insert(
            "0x605654e6946d0b0eeb55fcfde27edf897da863fa3451054ad41c0d12071def21".to_string(),
            "trin-nyc1-15".to_string(),
        );
        nicknames.insert(
            "0x5216adc06e287977518fa2eb305bfc81e101a2b07ecf73573851c0dd077ccfa7".to_string(),
            "trin-sgp1-13".to_string(),
        );
        nicknames.insert(
            "0x769f4d5ca128b3b732aae16581296e7f1d236ec4712f3d5f67d74a3f0e560737".to_string(),
            "trin-ams3-18".to_string(),
        );
        nicknames.insert(
            "0x2aa6d8bf210c6680a8a032257391ade71a53be5e9df5704f27a3bfb7f75a205f".to_string(),
            "trin-ams3-9".to_string(),
        );
        nicknames.insert(
            "0x33d0654d3eb85d874b25166f9de0013a331215a4ebf707f157762f1b7ec1008c".to_string(),
            "trin-ams3-10".to_string(),
        );
        nicknames.insert(
            "0x0edacae07480459447ff8938e619086a11535da1843a0f2a2991311c98e612d3".to_string(),
            "trin-sgp1-5".to_string(),
        );
        nicknames.insert(
            "0xcd9e479273522c08a947c90d2fcbb8d99ecf3babd51095d18d6cfb9eb2270126".to_string(),
            "trin-nyc1-28".to_string(),
        );
        nicknames.insert(
            "0xe41979cbd58a0976b24f945d3319b1723a643be425b42df3bf69f8551d8cf32a".to_string(),
            "trin-ams3-31".to_string(),
        );
        nicknames.insert(
            "0x38237bd265aa76632c88d1d05287084bd02bfb09fd7a35b33decb244a46a99df".to_string(),
            "trin-sgp1-10".to_string(),
        );
        nicknames.insert(
            "0xfd01ad3a29d55e4922eb3f647dc29753a0b58327a0d79661cce891a863e6e7af".to_string(),
            "trin-nyc1-35".to_string(),
        );
        nicknames.insert(
            "0xf5c57402370cf9b77101a3b58da8b4527104b34942f53bb942c84955f30d1da5".to_string(),
            "trin-ams3-34".to_string(),
        );
        nicknames.insert(
            "0xefd72017d61349b8d67c9e9133a72752c6bf62ad423736bbca7fffbbeae2e619".to_string(),
            "trin-ams3-33".to_string(),
        );
        nicknames.insert(
            "0xe7bd23ff5cdd02351791da0087bbbfb60067eb6f75b6492ba9c6885e1b694d0a".to_string(),
            "trin-nyc1-31".to_string(),
        );
        nicknames.insert(
            "0xb7a79e63510cc18ed8b6c9c9cdd14d539c582a5a55c3b1b593198f4851bd71b5".to_string(),
            "trin-sgp1-25".to_string(),
        );
        nicknames.insert(
            "0x8141bb6328eaba0c215e6a1aa24d9e63af9c3fe288567e38dd1e9ebaf53bb066".to_string(),
            "trin-nyc1-19".to_string(),
        );
        nicknames.insert(
            "0x9bd5f31dcb19bac10077cc903b651d1885807907b256bb497e683715bac20a66".to_string(),
            "trin-nyc1-22".to_string(),
        );
        nicknames.insert("0x00c9..98c1".to_string(), "trin-ams3-2".to_string());
        nicknames.insert("0x556d..2c4f".to_string(), "trin-nyc1-2".to_string());
        nicknames.insert("0xab0f..4408".to_string(), "trin-sgp1-2".to_string());
        nicknames.insert("0x00ff..7965".to_string(), "trin-ams3-3".to_string());
        nicknames.insert("0x55a7..d4bc".to_string(), "trin-nyc1-3".to_string());
        nicknames.insert("0xab0e..2946".to_string(), "trin-sgp1-3".to_string());
        nicknames.insert("0xe419..f32a".to_string(), "trin-ams3-31".to_string());
        nicknames.insert("0xe95d..0c09".to_string(), "trin-ams3-32".to_string());
        nicknames.insert("0xefd7..e619".to_string(), "trin-ams3-33".to_string());
        nicknames.insert("0xf5c5..1da5".to_string(), "trin-ams3-34".to_string());
        nicknames.insert("0xfae2..343a".to_string(), "trin-ams3-35".to_string());
        nicknames.insert("0x93c0..9bd8".to_string(), "trin-ams3-36".to_string());
        nicknames.insert("0xed31..c6f3".to_string(), "trin-ams3-37".to_string());
        nicknames.insert("0x66df..f1cd".to_string(), "trin-ams3-38".to_string());
        nicknames.insert("0xd7eb..bfbd".to_string(), "trin-ams3-39".to_string());
        nicknames.insert("0xe557..8834".to_string(), "trin-ams3-40".to_string());
        nicknames.insert("0xbdbb..3c8c".to_string(), "trin-ams3-41".to_string());
        nicknames.insert("0x7a51..13e2".to_string(), "trin-ams3-42".to_string());
        nicknames.insert("0x4aca..0305".to_string(), "trin-ams3-43".to_string());
        nicknames.insert("0x996c..dd21".to_string(), "trin-ams3-44".to_string());
        nicknames.insert("0xa7c9..ab0c".to_string(), "trin-ams3-45".to_string());
        nicknames.insert("0xfd01..e7af".to_string(), "trin-nyc1-35".to_string());
        nicknames.insert("0xd1b9..22a9".to_string(), "trin-nyc1-36".to_string());
        nicknames.insert("0x0cbb..5e2d".to_string(), "trin-nyc1-37".to_string());
        nicknames.insert("0xdf29..4c4e".to_string(), "trin-nyc1-38".to_string());
        nicknames.insert("0x5b18..34b0".to_string(), "trin-nyc1-39".to_string());
        nicknames.insert("0x1556..5049".to_string(), "trin-nyc1-40".to_string());
        nicknames.insert("0x392e..47f6".to_string(), "trin-nyc1-41".to_string());
        nicknames.insert("0xc37e..9314".to_string(), "trin-nyc1-42".to_string());
        nicknames.insert("0xdc2c..3ab6".to_string(), "trin-nyc1-43".to_string());
        nicknames.insert("0x2392..07dd".to_string(), "trin-nyc1-44".to_string());
        nicknames.insert("0x126f..7243".to_string(), "trin-nyc1-45".to_string());
        nicknames.insert("0x88dd..a5cb".to_string(), "trin-sgp1-31".to_string());
        nicknames.insert("0x2889..9df1".to_string(), "trin-sgp1-32".to_string());
        nicknames.insert("0xaf58..8f87".to_string(), "trin-sgp1-33".to_string());
        nicknames.insert("0x1a8a..8b2a".to_string(), "trin-sgp1-34".to_string());
        nicknames.insert("0x3c7e..e4ff".to_string(), "trin-sgp1-35".to_string());
        nicknames.insert("0x2bd9..1403".to_string(), "trin-sgp1-36".to_string());
        nicknames.insert("0xc6ea..e272".to_string(), "trin-sgp1-37".to_string());
        nicknames.insert("0x6fdb..419e".to_string(), "trin-sgp1-38".to_string());
        nicknames.insert("0x8526..2fe7".to_string(), "trin-sgp1-39".to_string());
        nicknames.insert("0x8234..0ed8".to_string(), "trin-sgp1-40".to_string());

        nicknames.insert(
            "0x9e7dc510a091a46a07a9d337f4b451eee499503b194b80228a7b9715c579e865".to_string(),
            "fluffy-ih-eu-mda-01-01 (bootnode)".to_string(),
        );
        nicknames.insert(
            "0xb46b09a36e2318900e142c36128b39651eb8ff908f1fe6830e7b3cd343f18ed3".to_string(),
            "fluffy-ih-eu-mda-01-02 (bootnode)".to_string(),
        );
        nicknames.insert(
            "0x42b0e92b8f1337516004b45ede9dae49d693db1e2bf45fceb239763a053555a7".to_string(),
            "fluffy-ih-eu-mda-01-03".to_string(),
        );
        nicknames.insert(
            "0xd953f61d98db5e1b8cade59cf6916c11094029bb8269e5de7a47765c029e333b".to_string(),
            "fluffy-ih-eu-mda-01-04".to_string(),
        );
        nicknames.insert(
            "0x1b824647b496fb3395014404c871569394db958e90a94c91816e81ff599cb4ed".to_string(),
            "fluffy-ih-eu-mda-01-05".to_string(),
        );
        nicknames.insert(
            "0x53f08e3cf92b770155d107aec8e95a4e5f8ce18f651579adcf53732b03ee9bbe".to_string(),
            "fluffy-ih-eu-mda-01-06".to_string(),
        );
        nicknames.insert(
            "0x8946f27752e6f7d7e219db3c5fa101e51ddacc79a4e0eb45646971be524e67e6".to_string(),
            "fluffy-ih-eu-mda-01-07".to_string(),
        );
        nicknames.insert(
            "0x1ccc27db08975e0f9a0322831457010eb5df1405c12a0a0f79b114c5a17bb4d6".to_string(),
            "fluffy-ih-eu-mda-01-08".to_string(),
        );
        nicknames.insert(
            "0x8c2ec98eb39be82a017722e656c4a8500a74ea1524f8d41c71e308651cc8e6e4".to_string(),
            "fluffy-ih-eu-mda-01-09".to_string(),
        );
        nicknames.insert(
            "0x751ca67eb420f9554634e04949911776a92b21c9fe84826ac5db21089f3d0e2a".to_string(),
            "fluffy-ih-eu-mda-01-10".to_string(),
        );
        nicknames.insert(
            "0xdc93661de6e20e6175fed2bb6864653a9f4ead9867f5d271dcea0e3561a74156".to_string(),
            "fluffy-ih-eu-mda-01-11".to_string(),
        );
        nicknames.insert(
            "0xa28405b17e47b256a39413683211fbc349aa1973e4e1570b95f4b7e3a63ccf21".to_string(),
            "fluffy-ih-eu-mda-01-12".to_string(),
        );
        nicknames.insert(
            "0x0f6d4925f0b42aa994bba4a43b487659e9a9769b9369a39bccceed553efa451b".to_string(),
            "fluffy-ih-eu-mda-01-13".to_string(),
        );
        nicknames.insert(
            "0x3da2bfa42fb38f24957260a97ae870eea1d830fc98854190953ba2b43ef31ab9".to_string(),
            "fluffy-ih-eu-mda-01-14".to_string(),
        );
        nicknames.insert(
            "0xfcabaebcca08c22ac435dd2ce41c2b74cad53239b5a0b85d75d750bb72ca70a1".to_string(),
            "fluffy-ih-eu-mda-01-15".to_string(),
        );
        nicknames.insert(
            "0x2477ce0dbf5c88564707ac3ecc8240f947129ecdcb98ced0c62356903faffe04".to_string(),
            "fluffy-ih-eu-mda-01-16".to_string(),
        );
        nicknames.insert(
            "0xb66aa02e959ba7a24b3b24ba38df1b9a4e29a257f46f52e8510a0db1dbb19418".to_string(),
            "fluffy-ih-eu-mda-01-17".to_string(),
        );
        nicknames.insert(
            "0x73bd8a86fa27e9a5822a29370d84dd6432a67a72780f79f3e1ea796fd9e86d16".to_string(),
            "fluffy-ih-eu-mda-01-18".to_string(),
        );
        nicknames.insert(
            "0x515db84a043dd4380f8e9b83abc63e6de16988d219f9822f6d1077b504165d80".to_string(),
            "fluffy-ih-eu-mda-01-19".to_string(),
        );
        nicknames.insert(
            "0xa06e610b6c0f96edc41e1fe6baaa6c6b7cb6bc6133d21d49a43cd9d95b021ca8".to_string(),
            "fluffy-ih-eu-mda-01-20".to_string(),
        );
        nicknames.insert(
            "0x944ca5359881d5bd8ab044ea89517aaefc006b2ec2da406b14bb4eea780cb5e7".to_string(),
            "fluffy-ih-eu-mda-01-21".to_string(),
        );
        nicknames.insert(
            "0xeb5467e2f6e645622f199dfa8fcdac31d0f086a2a3bdabe510a18114332e4286".to_string(),
            "fluffy-ih-eu-mda-01-22".to_string(),
        );
        nicknames.insert(
            "0x852bba0e8799adbe325a59575047e52bb80c5ebcab2d21117c63dabdadcdbea7".to_string(),
            "fluffy-ih-eu-mda-01-23".to_string(),
        );
        nicknames.insert(
            "0x9a5f1d1ecee0904b287c0f97f52ffa21388a7d29bc99854d0cdfc86a0fe62e07".to_string(),
            "fluffy-ih-eu-mda-01-24".to_string(),
        );
        nicknames.insert(
            "0x1ae5b5e4de2be1f115b16666096e5b883c62c0f67b741a1692776b3fd5e3dff9".to_string(),
            "fluffy-ih-eu-mda-01-25".to_string(),
        );
        nicknames.insert(
            "0x3d59f8fc4fe8f1cd3ad8e719053a0a0ba097ac2769adf60ad0386bfce26d49fb".to_string(),
            "fluffy-ih-eu-mda-01-26".to_string(),
        );
        nicknames.insert(
            "0xce8111057ee4a18caef44cd0de13d888b41c82437dac165974c988bd355e7d8a".to_string(),
            "fluffy-ih-eu-mda-01-27".to_string(),
        );
        nicknames.insert(
            "0x7573ba07475e977cac943e799b6fbb1a3c6420adfe53e75cb48c053ddb883eaf".to_string(),
            "fluffy-ih-eu-mda-01-28".to_string(),
        );
        nicknames.insert(
            "0xf5e8e0a0c0c4054dfe6db426aa7320ba3ab8e8c411d72fb043b15000ecf656d5".to_string(),
            "fluffy-ih-eu-mda-01-29".to_string(),
        );
        nicknames.insert(
            "0xc20a831f5579cdd373f3ca948d4edf91f5a411154174f123e70be244f8fb62c4".to_string(),
            "fluffy-ih-eu-mda-01-30".to_string(),
        );
        nicknames.insert(
            "0xf1fecf5055a4bab819b5a69120a632582e86953ad20fe106bb70b61ed36879a4".to_string(),
            "fluffy-ih-eu-mda-01-31".to_string(),
        );
        nicknames.insert(
            "0x754397264925c1e57e812697b976f2432c9c55df9ca8c7a6c7bde41cb076d86c".to_string(),
            "fluffy-ih-eu-mda-01-32".to_string(),
        );
        nicknames.insert(
            "0x9891fe3fdfcec2707f877306fc6e5596b1405fedf70ad2911496c2ac40dfeda5".to_string(),
            "fluffy-ih-eu-mda-02-01 (bootnode)".to_string(),
        );
        nicknames.insert(
            "0x122b3781acfd0145078e14ae9950c1a97004b481dc3c4ca00993f7d371f766cf".to_string(),
            "fluffy-ih-eu-mda-02-02 (bootnode)".to_string(),
        );
        nicknames.insert(
            "0xff05c3b85e6f03af44ed0e2b65f8a8a637a83158e227bed58d026ca745044407".to_string(),
            "fluffy-ih-eu-mda-02-03".to_string(),
        );
        nicknames.insert(
            "0xf3bb9ef410314982c6ff4dd2150363a4030f0beb0598f75b1a511a2850cf615b".to_string(),
            "fluffy-ih-eu-mda-02-04".to_string(),
        );
        nicknames.insert(
            "0x44ab745e5d5f30e76cb3eb93fd00d526f03ab8d231b26ecf8440341ba7d8c596".to_string(),
            "fluffy-ih-eu-mda-02-05".to_string(),
        );
        nicknames.insert(
            "0x42211e720dd1f12b3609b562417de3993c0f7e2f7bab8f95f6b6e06fbc002ebf".to_string(),
            "fluffy-ih-eu-mda-02-06".to_string(),
        );
        nicknames.insert(
            "0x6f241796a833fee515193c182da1c34d02ca4723a2e89020e376659e065752a9".to_string(),
            "fluffy-ih-eu-mda-02-07".to_string(),
        );
        nicknames.insert(
            "0xdd5b300689eae907a151372abc7efcedc55cf9bd9e0255e19e53a102b1695aa5".to_string(),
            "fluffy-ih-eu-mda-02-08".to_string(),
        );
        nicknames.insert(
            "0x80716944892be659a08aaf3516b71992ba0cd93fa8d705f0f6cd1fbd6f4fceed".to_string(),
            "fluffy-ih-eu-mda-02-09".to_string(),
        );
        nicknames.insert(
            "0xd07753ecb594a78065cceb98201ac3b3cf0bc6587f291a45efc0fee235f3f553".to_string(),
            "fluffy-ih-eu-mda-02-10".to_string(),
        );
        nicknames.insert(
            "0xf9fbbc55a5005eb707c2e61b88ab8be6e89c9e48818d5929930e28539faef76f".to_string(),
            "fluffy-ih-eu-mda-02-11".to_string(),
        );
        nicknames.insert(
            "0x47c1289e2e16d18c880ad57e5aff2b9ff3c0e1261385078f1a7b835fed90c159".to_string(),
            "fluffy-ih-eu-mda-02-12".to_string(),
        );
        nicknames.insert(
            "0x5dd2fba6c174a74cd815a884a7c33d92d79e6379ae2ffaaee749cdda0e2c922d".to_string(),
            "fluffy-ih-eu-mda-02-13".to_string(),
        );
        nicknames.insert(
            "0xbefb246b22757267608a436d265018374592291f284c536f73c933b29a91e10a".to_string(),
            "fluffy-ih-eu-mda-02-14".to_string(),
        );
        nicknames.insert(
            "0xf6579f040293c8b50aac41d1e4fda466aee0d4333a665c1a7609ea849d24c2ed".to_string(),
            "fluffy-ih-eu-mda-02-15".to_string(),
        );
        nicknames.insert(
            "0xc39d4d7f6da13d5f09b8bdec80ac4a46c566363d97ec19c7e906f234f6201346".to_string(),
            "fluffy-ih-eu-mda-02-16".to_string(),
        );
        nicknames.insert(
            "0x2d9b215a58a1070785b80838e623ba2539dd2d11baf104cc3a70eedc3dbe08c4".to_string(),
            "fluffy-ih-eu-mda-02-17".to_string(),
        );
        nicknames.insert(
            "0xcedf1766a9d14bc943570d216648d3068b97e229841b53d7ad31ca4da05442d0".to_string(),
            "fluffy-ih-eu-mda-02-18".to_string(),
        );
        nicknames.insert(
            "0x7d7e394a5759f1aefab323c7f2b3bf1a395377c6b40ba8600d0b598d40402276".to_string(),
            "fluffy-ih-eu-mda-02-19".to_string(),
        );
        nicknames.insert(
            "0xfe75f07712d827c4a2ece430d438d2038bc601c6ca264f16346af9e75648a38b".to_string(),
            "fluffy-ih-eu-mda-02-20".to_string(),
        );
        nicknames.insert(
            "0x76bbf3fbe47abc63938f755731141f4366363048e6442f43ab94a78b7649b842".to_string(),
            "fluffy-ih-eu-mda-02-21".to_string(),
        );
        nicknames.insert(
            "0xc0a75a934a9c0a4f65265f6a9cb480d9d3e67f3c0c551c5e6ea9ee238385e3cd".to_string(),
            "fluffy-ih-eu-mda-02-22".to_string(),
        );
        nicknames.insert(
            "0xcb4bc943038033488c2ecc39c47b49f338d434defa6832f71f73760f085764fe".to_string(),
            "fluffy-ih-eu-mda-02-23".to_string(),
        );
        nicknames.insert(
            "0xb94599625525916e57cc354b77bb85ed48a5cb5a00617ba973c13507643de182".to_string(),
            "fluffy-ih-eu-mda-02-24".to_string(),
        );
        nicknames.insert(
            "0x096b4ecca95b7e97a5a864c9de84a144969c25e9e5dd1045df222244841c306b".to_string(),
            "fluffy-ih-eu-mda-02-25".to_string(),
        );
        nicknames.insert(
            "0xd48a2bc637251167e5a4b6e7f0fa04ac18dad38c034ce2b695135d86c01e7ec9".to_string(),
            "fluffy-ih-eu-mda-02-26".to_string(),
        );
        nicknames.insert(
            "0x149c178cd1839c0f0f80cea4c7d67e503924a54b9a5a339043256a8d52187110".to_string(),
            "fluffy-ih-eu-mda-02-27".to_string(),
        );
        nicknames.insert(
            "0x625326c16d08b47a6f51c09c6446265933c0d10cf9f38662468fac4658f8431b".to_string(),
            "fluffy-ih-eu-mda-02-28".to_string(),
        );
        nicknames.insert(
            "0xf3df94b51c551c08664be23d61df97f9cf3ae67b2b1a0dc9ca4b202b103aeed6".to_string(),
            "fluffy-ih-eu-mda-02-29".to_string(),
        );
        nicknames.insert(
            "0xbdb139d945d8ae846aff8017680a5257e84b75cb4fe35ed82a9c10cd0d518f79".to_string(),
            "fluffy-ih-eu-mda-02-30".to_string(),
        );
        nicknames.insert(
            "0xeb4e1d41d601da46e66323741f80cbad7cbeddc416e5becc3d570eec996598e6".to_string(),
            "fluffy-ih-eu-mda-02-31".to_string(),
        );
        nicknames.insert(
            "0xdcba4606925c9803b8fbfda1d6a354ad195ab801ce6706f3ffd2867d2937c02f".to_string(),
            "fluffy-ih-eu-mda-02-32".to_string(),
        );
        nicknames.insert(
            "0xef75a4aecf52f34f90f14042bbc002075c3fe323eb24803629953083053c0320".to_string(),
            "ultralight bootnode 1".to_string(),
        );
        nicknames.insert(
            "0xb11a574cb4eef79fea7b15ffecdff26638592fbf9fec235172b23fd9ef4305d8".to_string(),
            "ultralight bootnode 2".to_string(),
        );
        nicknames.insert(
            "0x8148d0278d49015995847572da4fa8f0a981b7fb57774a7d3d40c985529f3237".to_string(),
            "ultralight bootnode 3".to_string(),
        );
        nicknames.insert(
            "0x95c8df0a57c901c5d4561403a77067996b03b64e7beb1bdee662fae236d2188c".to_string(),
            "ultralight bootnode 4".to_string(),
        );

        nicknames
    };
    pub static ref BOOTNODE_NICKNAMES: HashMap<String, String> = {
        NODE_NICKNAME_MAP
            .iter()
            .filter(|(_, nickname)| nickname.contains("bootnode"))
            .map(|(id, nickname)| (id.clone(), nickname.clone()))
            .collect()
    };
}
